services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - squid_network
    restart: unless-stopped

networks:
  squid_network:
    driver: bridge
